version: "3.7"
services:
        jupyter:
                build: .
                ports:
                        - "8888:8888"
                volumes:
                        - type: bind
                          source: ./notebooks
                          target: /home/jovyan/work
                          volume:
                                  nocopy: true
volumes:
        notebooks:
